version: '3'

services:
  server:
    build: ./server
    ports:
    - "3000:3000"
    command: npm start
    volumes:
    - ./server:/app
    - /app/node_modules
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rule-saga
  client:
    build:
      context: ./client
      args:
      - NODE_ENV=development
    ports:
    - "1233:1233"
    - "1234:1234"
    - "3010:3001"
    - "38771:38771"
    command: npm start
    volumes:
    - ./client:/app
    - /app/node_modules
    environment:
    - NODE_ENV=development
    depends_on:
    - server
